[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self';"

[[plugins]]
package = "netlify-plugin-checklinks"

[[plugins]]
package = "netlify-plugin-gatsby-cache"
